app:
  log_file: "bailiff.log"
  log_level: "INFO"
  data_dir: "data"

audio:
  sample_rate: 16000 # Sample rate for audio processing
  chunk_size: 512 # Size of audio chunks
  vad_threshold: 0.5 # Threshold for voice activity detection
  silence_limit: 1.0 # Limit for silence duration

models:
  llm_provider: "ollama" 
  llm_base_url: "http://localhost:11434/v1" # You can use any OpenAI compatible API
  llm_assistant: "llama3.2"
  llm_digestion: "llama3.2"
  llm_summary: "llama3.2"
  voice_embedding: "speechbrain/spkrec-ecapa-voxceleb"

diarization:
  threshold: 0.5 # Similarity threshold for speaker diarization
  inertia_weight: 0.1 # Weight added for previous speaker 
  merge_timeout: 8.0 # Timeout for merging speaker segments
  segment_timeout: 3.0 # Timeout for speaker segments

transcription:
  model_size: "small" # For GPU i recommend "deepdml/faster-whisper-large-v3-turbo-ct2" 
  device: "cpu" # For GPU i recommend "cuda" 
  compute_type: "int8" # For GPU i recommend "float16"
  language: en # Set a language code (e.g. "pt", "en", "es") or leave null for auto-detect
