app:
  log_file: "bailiff.log"
  log_level: "INFO"
  data_dir: "data"

audio:
  sample_rate: 16000 # Sample rate for audio processing
  chunk_size: 512 # Size of audio chunks
  vad_threshold: 0.5 # Threshold for voice activity detection
  silence_limit: 1.0 # Limit for silence duration
  speech_pad_ms: 200 # Padding for speech segments

models:
  llm_provider: "deepseek" 
  llm_base_url: "https://api.deepseek.com/v1" # You can use any OpenAI compatible API
  llm_assistant: "deepseek-chat"
  llm_digestion: "deepseek-chat"
  llm_summary: "deepseek-chat"
  voice_embedding: "speechbrain/spkrec-ecapa-voxceleb"

diarization:
  threshold: 0.5 # Similarity threshold for speaker diarization
  inertia_weight: 0.1 # Weight added for previous speaker 
  merge_timeout: 8.0 # Timeout for merging speaker segments
  segment_timeout: 3.0 # Timeout for speaker segments

transcription:
  model_size: "deepdml/faster-whisper-large-v3-turbo-ct2" # For GPU i recommend "deepdml/faster-whisper-large-v3-turbo-ct2" 
  device: "cuda" # For GPU i recommend "cuda" 
  compute_type: "float16" # For GPU i recommend "float16"
